{
 "title": "Tinkoff Investing",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Item", "query": { "query": "label_values(tcs_item, name)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Portfolio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\"}) + Sum(tcs_yield{balance_currency=\"RUB\",account=~\"T.*\"})",
     "legendFormat": "RUB"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"USD\",account=~\"T.*\"}) + Sum(tcs_yield{balance_currency=\"USD\",account=~\"T.*\"})",
     "legendFormat": "USD"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"EUR\",account=~\"T.*\"}) + Sum(tcs_yield{balance_currency=\"EUR\",account=~\"T.*\"})",
     "legendFormat": "EUR"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "tcs_rate{currency=~\"EURRUB|USDRUB\"}"
    }
   ]
  },
  {
   "title": "Portfolio, RUB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "Sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\"}) + Sum(tcs_yield{balance_currency=\"RUB\",account=~\"T.*\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\"})",
     "legendFormat": "Invested"
    }
   ]
  },
  {
   "title": "Tinkoff",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Sum(tcs_item{balance_currency=\"RUB\",account=\"Tinkoff\"}) + Sum(tcs_yield{balance_currency=\"RUB\",account=\"Tinkoff\"})",
     "legendFormat": "RUB"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"USD\",account=\"Tinkoff\"}) + Sum(tcs_yield{balance_currency=\"USD\",account=\"Tinkoff\"})",
     "legendFormat": "USD"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"EUR\",account=\"Tinkoff\"}) + Sum(tcs_yield{balance_currency=\"EUR\",account=\"Tinkoff\"})",
     "legendFormat": "EUR"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "Sum(tcs_item{balance_currency=\"RUB\"}) by (account) + Sum(tcs_yield{balance_currency=\"RUB\"}) by (account)",
     "legendFormat": "RUB"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"USD\"}) by (account) + Sum(tcs_yield{balance_currency=\"USD\"}) by (account)",
     "legendFormat": "USD"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"EUR\"}) by (account) + Sum(tcs_yield{balance_currency=\"EUR\"}) by (account)",
     "legendFormat": "EUR"
    }
   ]
  },
  {
   "title": "Portfolio, USD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "Sum(tcs_item{balance_currency=\"USD\",account=~\"T.*\"}) + Sum(tcs_yield{balance_currency=\"USD\",account=~\"T.*\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"USD\",account=~\"T.*\"})",
     "legendFormat": "Invested"
    }
   ]
  },
  {
   "title": "Tinkoff IIS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Sum(tcs_item{balance_currency=\"RUB\",account=\"TinkoffIis\"}) + Sum(tcs_yield{balance_currency=\"RUB\",account=\"TinkoffIis\"})",
     "legendFormat": "RUB"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"USD\",account=\"TinkoffIis\"}) + Sum(tcs_yield{balance_currency=\"USD\",account=\"TinkoffIis\"})",
     "legendFormat": "USD"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"EUR\",account=\"TinkoffIis\"}) + Sum(tcs_yield{balance_currency=\"EUR\",account=\"TinkoffIis\"})",
     "legendFormat": "EUR"
    }
   ]
  },
  {
   "title": "Profit/Loss",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "Sum(tcs_yield{balance_currency=\"RUB\"}) by (account)",
     "legendFormat": "RUB"
    },
    {
     "expr": "Sum(tcs_yield{balance_currency=\"USD\"}) by (account)",
     "legendFormat": "USD"
    },
    {
     "expr": "Sum(tcs_yield{balance_currency=\"EUR\"}) by (account)",
     "legendFormat": "EUR"
    },
    {
     "expr": "Sum(tcs_yield{balance_currency=\"RUB\"}) by (account) / Sum(tcs_item{balance_currency=\"RUB\"}) by (account) * 100",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Portfolio w/o Currency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "Sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\",type!=\"Currency\"}) + Sum(tcs_yield{balance_currency=\"RUB\",account=~\"T.*\",type!=\"Currency\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "Sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\",type!=\"Currency\"})",
     "legendFormat": "Invested"
    }
   ]
  },
  {
   "title": "P/L w/o Currency",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "Sum(tcs_yield{balance_currency=\"RUB\",account=~\"T.*\",type!=\"Currency\"}) by (account)",
     "legendFormat": "RUB"
    },
    {
     "expr": "Sum(tcs_yield{balance_currency=\"USD\",account=~\"T.*\",type!=\"Currency\"}) by (account)",
     "legendFormat": "USD"
    },
    {
     "expr": "Sum(tcs_yield{balance_currency=\"EUR\",account=~\"T.*\",type!=\"Currency\"}) by (account)",
     "legendFormat": "EUR"
    },
    {
     "expr": "Sum(tcs_yield{balance_currency=\"RUB\",account=~\"T.*\",type!=\"Currency\"}) by (account) / Sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\",type!=\"Currency\"}) by (account) * 100",
     "legendFormat": "Percent"
    }
   ]
  },
  { "title": "Currency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tcs_rate{currency=~\"USDRUB\"}",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "EUR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tcs_rate{currency=~\"EURRUB\"}",
     "legendFormat": "EUR"
    }
   ]
  },
  { "title": "Брокерский", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Текущий доход в рублях",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "sort(sum(tcs_yield{account=~\"Tinkoff\",balance_currency=\"RUB\"}) by (name))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum(tcs_yield{account=~\"Tinkoff\",balance_currency=\"RUB\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Брокерский счет",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{account=\"Tinkoff\",balance_currency=\"USD\"}) by (name) + sum(tcs_yield{account=\"Tinkoff\",balance_currency=\"USD\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Диверсификация портфеля",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyUSD",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"Tinkoff\", currency=\"RUB\"}) by (type) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"Tinkoff\", currency=\"RUB\"}) by (type)",
     "legendFormat": "{{ type }}, RUB"
    },
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"Tinkoff\", currency=\"USD\"}) by (type) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"Tinkoff\", currency=\"USD\"}) by (type)",
     "legendFormat": "{{type}}, USD"
    },
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"Tinkoff\", currency=\"EUR\"}) by (type) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"Tinkoff\", currency=\"EUR\"}) by (type)",
     "legendFormat": "{{type}}, EUR"
    }
   ]
  },
  {
   "title": "Currency",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Currency\",account=~\"Tinkoff\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{type=\"Currency\",account=~\"Tinkoff\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "ИИС", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Текущий доход в рублях",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "sort(sum(tcs_yield{account=~\"TinkoffIis\",balance_currency=\"RUB\"}) by (name))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum(tcs_yield{account=~\"TinkoffIis\",balance_currency=\"RUB\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "ИИС",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{account=\"TinkoffIis\",balance_currency=\"USD\"}) by (name) + sum(tcs_yield{account=\"TinkoffIis\",balance_currency=\"USD\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Диверсификация портфеля",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyUSD",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"TinkoffIis\", currency=\"RUB\"}) by (type) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"TinkoffIis\", currency=\"RUB\"}) by (type)",
     "legendFormat": "{{ type }}, RUB"
    },
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"TinkoffIis\", currency=\"USD\"}) by (type) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"TinkoffIis\", currency=\"USD\"}) by (type)",
     "legendFormat": "{{type}}, USD"
    },
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"TinkoffIis\", currency=\"EUR\"}) by (type) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"TinkoffIis\", currency=\"EUR\"}) by (type)",
     "legendFormat": "{{type}}, EUR"
    }
   ]
  },
  {
   "title": "Currency",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Currency\",account=~\"TinkoffIis\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{type=\"Currency\",account=~\"TinkoffIis\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "ETF",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Etf\",account=~\"TinkoffIis\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{type=\"Etf\",account=~\"TinkoffIis\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Stocks",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Stock\",account=~\"TinkoffIis\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{type=\"Stock\",account=~\"TinkoffIis\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Bonds",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Bond\",account=~\"TinkoffIis\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{type=\"Bond\",account=~\"TinkoffIis\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "item info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Current position and yield - $Item",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{name=\"$Item\",balance_currency=\"RUB\"}) + sum(tcs_yield{name=\"$Item\",balance_currency=\"RUB\"})",
     "legendFormat": "RUB"
    },
    {
     "expr": "Sum(tcs_item{name=\"$Item\",balance_currency=\"USD\"}) + sum(tcs_yield{name=\"$Item\",balance_currency=\"USD\"})",
     "legendFormat": "USD"
    },
    {
     "expr": "sum(tcs_item{name=\"$Item\",balance_currency=\"EUR\"}) + sum(tcs_yield{name=\"$Item\",balance_currency=\"EUR\"})",
     "legendFormat": "EUR"
    },
    {
     "expr": "sum(tcs_yield{name=\"$Item\",balance_currency=\"RUB\"})",
     "legendFormat": "RUB"
    },
    {
     "expr": "sum(tcs_yield{name=\"$Item\",balance_currency=\"USD\"})",
     "legendFormat": "USD"
    },
    {
     "expr": "sum(tcs_yield{name=\"$Item\",balance_currency=\"EUR\"})",
     "legendFormat": "EUR"
    }
   ]
  },
  {
   "title": "$Item",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "sum(tcs_item{name=\"$Item\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{name=\"$Item\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(tcs_item{name=\"$Item\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "Invested"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Текущий доход в рублях",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "sort(sum(tcs_yield{account=~\"T.*\",balance_currency=\"RUB\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Текущий доход в USD",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sort(sum(tcs_yield{account=~\"T.*\",balance_currency=\"USD\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Pie charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Весь портфель",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\"}) by (name) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"T.*\"}) by (name)"
    }
   ]
  },
  {
   "title": "Диверсификация портфеля",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyUSD",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\", currency=\"RUB\"}) by (type) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"T.*\", currency=\"RUB\"}) by (type)",
     "legendFormat": "{{ type }}, RUB"
    },
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\", currency=\"USD\"}) by (type) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"T.*\", currency=\"USD\"}) by (type)",
     "legendFormat": "{{type}}, USD"
    },
    {
     "expr": "sum(tcs_item{balance_currency=\"RUB\",account=~\"T.*\", currency=\"EUR\"}) by (type) + sum(tcs_yield{balance_currency=\"RUB\",account=~\"T.*\", currency=\"EUR\"}) by (type)",
     "legendFormat": "{{type}}, EUR"
    }
   ]
  },
  {
   "title": "ETF",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Etf\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{type=\"Etf\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Bonds",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Bond\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{type=\"Bond\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Stocks",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Stock\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{type=\"Stock\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Currency",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "format": "currencyRUB",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tcs_item{type=\"Currency\",balance_currency=\"RUB\"}) by (name) + sum(tcs_yield{type=\"Currency\",balance_currency=\"RUB\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}